#' The World Happiness Report
#'
#' Data from the World Happiness Report on 161 countries from 2005 to 2016.
#'
#' @format A tibble with 1420 observations and 19 variables:
#' \itemize{
#'   \item ID. A factor indicating the country pair (ISO3 code) and the year.
#'   \item Country. Factor indicating the country (ISO3 code).
#'   \item year. Integer indicating the year. 
#'   \item Life_Ladder. Numeric. This variable is a measure of "Happiness score or subjective well-being: The survey measure of SWB is from the Dec 23, 2016 release of the Gallup World Poll (GWP), which covers the years from 2005 to 2016. Unless stated otherwise, it is the national average response to the question of life evaluations. The English wording of the question is “Please imagine a ladder, with steps numbered from 0 at the bottom to 10 at the top. The top of the ladder represents the best possible life for you and the bottom of the ladder represents the worst possible life for you. On which step of the ladder would you say you personally feel you stand at this time?”" (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Log_GDP_per_capita. Numeric. "The statistics of GDP per capita in purchasing power parity (PPP) at constant 2011 international dollar prices are from the August 10, 2016 release of the World Development Indicators (WDI). The GDP figures for Taiwan are from the Penn World Table 7.1. Syria and Argentina are missing the GDP numbers in the WDI release but were present in earlier releases. We use the numbers from the earlier release, after adjusting their levels by a factor of 1.17 to take into account changes in the implied prices when switching from the PPP 2005 prices used in the earlier release to the PPP 2011 prices used in the latest release. The factor of 1.17 is the average ratio derived by dividing the US GDP per capita under the 2011 prices with their counterparts under the 2005 prices." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Social_support. Numeric. "Social support (or having someone to count on in times of trouble) is the national average of the binary responses (either 0 or 1) to the GWP question “If you were in trouble, do you have relatives or friends you can count on to help you whenever you need them, or not?”" (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Healthy_life_expectancy_at_birth. Numeric. "Healthy Life Expectancy (HLE). The time series of healthy life expectancy at birth are calculated by the authors based on data from the World Health Organization (WHO), the World Development Indicators (WDI), and statistics published in journal articles. The challenge is that the healthy life expectancy, unlike the simple life expectancy, is not widely available as time series. In the WHO’s Global Health Observatory Data Repository, the statistics of healthy life expectancy are reported only for the years of 2000 and 2012. In our effort to derive the time series of healthy life expectancy for our sample period (2005 to 2016), we use WDI’s non-health adjusted life expectancy, which is available as time series up to the year 2014, as the basis of our calculation. Using country-specific ratios of healthy life expectancy to total life expectancy in 2012, available from the WHO, we adjust the time series of total life expectancy to healthy life expectancy by simple multiplication, assuming that the ratio remains constant within each country over the sample period. Three countries/regions are missing due to the lack of health/total life expectancy ratio. One is Hong Kong. We calculate its ratio using relevant estimates in “Healthy life expectancy in Hong Kong Special Administrative Region of China,” by C.K. Law, & P.S.F. Yip, published at the Bulletin of the World Health Organization, 2003, 81 (1).  Another is Puerto Rico.  We set its ratio to the U.S. ratio of 0.886. The third is Kosovo, we set its ratio to the world average. The estimated life expectancy for Taiwan and the Palestinian Territories are available in “Healthy life expectancy for 187 countries, 1990 - 2010: a systematic analysis for the Global Burden Disease Study 2010,” by Joshua A Salomon et al, The Lancet, Volume 380, Issue 9859. Once we have the data, we use intrapolation and extrapolation to fill in the missing values (when necessary) and to extend the period to 2016. Not all the countries/territories mentioned above are necessarily included in the most recent happiness ranking. The HLE is constructed regardless of a country/territory’s presence in a particular ranking." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Freedom_to_make_life_choices. Numeric. "Freedom to make life choices is the national average of responses to the GWP question “Are you satisfied or dissatisfied with your freedom to choose what you do with your life?”" (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Generosity. Numeric. "Generosity is the residual of regressing national average of response to the GWP question “Have you donated money to a charity in the past month?” on GDP per capita." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Perceptions_of_corruption. Numeric. "The measure is the national average of the survey responses to two questions in the GWP: “Is corruption widespread throughout the government or not” and “Is corruption widespread within businesses or not?” The overall perception is just the average of the two 0-or-1 responses. In case the perception of government corruption is missing, we use the perception of business corruption as the overall perception. The corruption perception at the national level is just the average response of the overall perception at the individual level." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Positive_affect. Numeric. "Positive affect is defined as the average of three positive affect measures in GWP: happiness, laugh and enjoyment in the Gallup World Poll waves 3-7. These measures are the responses to the following three questions, respectively: “Did you experience the following feelings during A LOT OF THE DAY yesterday? How about Happiness?”, “Did you smile or laugh a lot yesterday?”, and “Did you experience the following feelings during A LOT OF THE DAY yesterday? How about Enjoyment?” Waves 3-7 cover years 2008 to 2012 and a small number of countries in 2013. For waves 1-2 and those from wave 8 on, positive affect is defined as the average of laugh and enjoyment only, due to the limited availability of happiness." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Negative_affect. Numeric. "Negative affect is defined as the average of three negative affect measures in GWP. They are worry, sadness and anger, respectively the responses to “Did you experience the following feelings during A LOT OF THE DAY yesterday? How about Worry?”, “Did you experience the following feelings during A LOT OF THE DAY yesterday? How about Sadness?”, and “Did you experience the following feelings during A LOT OF THE DAY yesterday? How about Anger?”" (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Confidence_in_national_government. Numeric. "Confidence in national government from the GWP. The English wording of the question is “Do you have confidence in each of the following, or not? How about the national government? (WP139)”" (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Democratic_Quality. Numeric. "Democratic and delivery quality measures of governance are based on Worldwide Governance Indicators (WGI) project (Kaufmann, Kraay and Mastruzzi).  The original data have six dimensions: Voice and Accountability, Political Stability and Absence of Violence, Government Effectiveness, Regulatory Quality, Rule of Law, Control of Corruption. The indicators are on a scale roughly with mean zero and a standard deviation of 1. We reduce the number of dimensions to two using the simple average of the first two measures as an indicator of democratic quality, and the simple average of the other four measures as an indicator of delivery quality, following Helliwell and Huang (2008)." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Delivery_Quality. Numeric. "Democratic and delivery quality measures of governance are based on Worldwide Governance Indicators (WGI) project (Kaufmann, Kraay and Mastruzzi).  The original data have six dimensions: Voice and Accountability, Political Stability and Absence of Violence, Government Effectiveness, Regulatory Quality, Rule of Law, Control of Corruption. The indicators are on a scale roughly with mean zero and a standard deviation of 1. We reduce the number of dimensions to two using the simple average of the first two measures as an indicator of democratic quality, and the simple average of the other four measures as an indicator of delivery quality, following Helliwell and Huang (2008)." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Standard_deviation_of_ladder_by_country.year. Numeric. "Alternative measures of inequality in happiness scores by wp5-year. These extra measures are sdLadder “Standard deviation of ladder by country-year” and cvLadder “Standard deviation/Mean of ladder by country-year”." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item Standard_deviation.Mean_of_ladder_by_country.year. Numeric. "Alternative measures of inequality in happiness scores by wp5-year. These extra measures are sdLadder “Standard deviation of ladder by country-year” and cvLadder “Standard deviation/Mean of ladder by country-year”." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item GINI_index_.World_Bank_estimate.._average_2000.13. Numeric. "According to the source, the data source is “World Bank, Development Research Group. Data are based on primary household survey data obtained from government statistical agencies and World Bank country departments.” The variable giniIncWB is an unbalanced panel of yearly index. The data availability is patchy at the yearly frequency. The variable giniIncWBavg is the average of giniIncWB in the period 2000-2013. The average does not imply that a country has the gini index in all years in that period. In fact, most do not." (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#'   \item gini_of_household_income_reported_in_Gallup._by_wp5.year. Numeric. "To calculate income, respondents are asked to report their household income in local currency. Those respondents who have difficulty answering the question are presented a set of ranges in local currency and are asked which group they fall into. Income variables are created by converting local currency to International Dollars (ID) using purchasing power parity (PPP) ratios.”" (source: http://worldhappiness.report/wp-content/uploads/sites/2/2017/03/StatisticalAppendixWHR2017.pdf)
#' }
#' @source \url{http://worldhappiness.report/ed/2017/}
#' @docType data
#' @keywords World Happiness Report
#' @name WorldHappinessReport
#' @usage data("WorldHappinessReport")
#' @references {Helliwell, J., Layard, R., & Sachs, J. (2017). World Happiness Report 2017, New York: Sustainable Development Solutions Network.}
"WorldHappinessReport"
